name: CI
on:
  pull_request:
    branches: [ percy-main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: yarn
    - name: Run tests
      uses: percy/exec-action@v0.3.1
        with:
          custom-command: "yarn workspace remix-core test:percy"
      env:
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}/