name: Playwright Tests
on:
  push:
    branches: [ playwright-main ]
  pull_request:
    branches: [ playwright-main ]
jobs:
  test_mac:
    name: ${{ matrix.os }} (${{ matrix.browser }})
    strategy:
      fail-fast: false
      matrix:
        os: [macos-11]
        browser: [chromium]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 14
    - run: npm i -g npm@8
    - run: yarn
    - run: npx playwright install --with-deps ${{ matrix.browser }} chromium
    - run: yarn playwright test -- --project=${{ matrix.browser }}
    - uses: actions/upload-artifact@v3
      if: ${{ always() }}
      with:
        name: ${{ matrix.browser }}-${{ matrix.os }}-test-results
        path: test-results
