name: Playwright Tests
on:
  push:
    branches: [ playwright-main ]
  pull_request:
    branches: [ playwright-main ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.28.0-focal
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: Install dependencies
      run: yarn
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: yarn playwright test
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: playwright-report
        path: /remix-core/playwright-report/
        retention-days: 30
